USE [ViagemDB]
GO
/****** Object: Table [dbo].[TB_VIAGEM] Script Date: 05/08/2016 17:32:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TB_VIAGEM](
[id] [int] IDENTITY(1,1) NOT NULL,
[descricao] [varchar](50) NULL,
[data] [datetime] NULL,
CONSTRAINT [PK_tb_viagem] PRIMARY KEY CLUSTERED
(
[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS =
ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_PADDING OFF
GO